### ISSUE TITLE
Installation via the Backdrop UI

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/potx#2] opened 2017-04-07 10:15 UTC
When I upload the zip of the module in the *Manual installation* pop up of  `admin/modules/install`, I get the following message and can't continue the installation:

> The info file (temporary://update-extraction-69971ec2/potx-1.x-3.x/tests/potx_test_6.info) does not define a 'type' attribute.

Workaround: Unzipped the module locally, renamed it to "potx" (without version number) and put it in the `/modules` folder.

**Comment by klonos** [comment] 2017-04-07 23:21
@serundeputy I see a lot of .yml files, a [/tests/drupal8](https://github.com/serundeputy/potx/tree/1.x-3.x/tests/drupal8) folder, and [mentions of using Symfony](https://github.com/serundeputy/potx/blob/1.x-3.x/potx.local.inc#L3) are you sure you branched from 7.x?

...although I do see `core = 7.x` in the module's .info file: https://github.com/serundeputy/potx/blob/1.x-3.x/potx.info#L8 Hmm.

**Comment by serundeputy** [comment] 2017-04-07 23:23
@klonos yes from `7.x`, but the `7.x` branch def had a lot of code to work with D8, much of it removed here, but not all.

**Comment by serundeputy** [comment] 2017-04-07 23:24
`7.x-3.x`
http://cgit.drupalcode.org/potx/log/

**Comment by klonos** [comment] 2017-04-07 23:24
[6.x as well as it seems](https://github.com/serundeputy/potx/blob/1.x-3.x/tests/potx_test_6.info#L5): `core = 6.x` ...not sure what's going on with that project's code.

**Comment by serundeputy** [comment] 2017-04-07 23:26
@olafgrabienski I can put in the type=module lines in the `test` modules.

yes the one version of `potx` in drupal land is capable of exporting language strings from 5.x, 6.x, 7.x and 8.x Drupals.

**Comment by klonos** [comment] 2017-04-07 23:46
Hmm, it does make sense then. ...at least in Drupal-land.

Worthy noting these from the d.org queue:

[Wrong PHP version requirement in .info file [#2521630]](https://www.drupal.org/node/2521630)

[Refactor the structure of Potx [#2346345]](https://www.drupal.org/node/2346345):

> Unpostponing.

>l.d.o has been upgraded to D7 and now there is no longer a need to keep 6.x code in sync if functionality is 100% the same. I guess this syncing was only because of l10n_server integration for very good reasons, but these no longer exists in reality.

>Let's move on and simplify the code.

[Extracting Drupal 8 translations with POTX [#2356469]](https://www.drupal.org/node/2356469)

Hmm again. Not sure we need all the complexity the drupal version of potx is adding for the sake of supporting D6 and D8.

**Comment by serundeputy** [comment] 2017-04-07 23:49
this port does not support any of the drupals.

**Comment by quicksketch** [comment] 2017-12-01 00:37
Confirmed this module doesn't currently work via the installer, it's because it contains a bunch of D6 and D7 style code and .info files for testing purposes. As we don't need to support Drupal versions in our own POTX module, we can remove those tests and parsing routines. This should be fixed at the same time as https://github.com/backdrop-contrib/potx/issues/5.

**Comment by quicksketch** [comment] 2017-12-01 05:53
I've merged in #5 but this problem still isn't fixed.

One more minor change needed: Add `type = module` to the potx_test.info file. PR at https://github.com/backdrop-contrib/potx/pull/7

**Comment by olafgrabienski** [comment] 2017-12-07 16:47
Confirmed: I'm able to install the module in the *Manual installation* pop up of `admin/modules/install` now.

**Comment by olafgrabienski** [comment] 2017-12-07 22:11
Wait, I've tried to install the module on another environment, and now the installer gave me an error message about another missing `type` attribute: `The info file (temporary://update-extraction-(...)/potx-1.x-3.x/tests/potx.tests.info) does not define a 'type' attribute.`

So, `potx_test.info` is fixed, but `potx.tests.info` not.

**Comment by quicksketch** [comment] 2017-12-10 06:36
Thanks @olafgrabienski! Could you try one more time? I've updated the code to now move the test module into its own directory, that may prevent that error.

**Comment by olafgrabienski** [comment] 2017-12-11 10:27
Thank *you*! I was able to install the module with the updated code in the *Manual installation* pop up without any issue.

**Comment by quicksketch** [comment] 2018-08-09 20:17
This looks like it's solved then!

**Closed as completed by quicksketch** 2018-08-09 20:17 UTC
